# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Scan Application"
  lane :scan do
    sonar(
        project_key: "hello2",
        project_version: "1.0",
        project_name: "hello2",
        sonar_sources: "."
        sonar_url: "http://localhost:9000"
        sonar_login: "hello2"
    )
  end

  desc "Build Application"
    lane :build do
    gradle(task: 'assemble', build_type: 'Debug')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
